name: Auto-format Code

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: Auto-format with forge fmt
    runs-on: ubuntu-latest
    
    # Skip if the last commit was from this action to avoid loops
    if: github.event.pull_request.head.repo.full_name == github.repository && !contains(github.event.head_commit.message, '[auto-format]')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Run forge fmt
        run: forge fmt
      
      - name: Check for changes
        id: git-check
        run: |
          if git diff --exit-code; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No formatting changes needed"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Formatting changes detected"
          fi
      
      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "chore: auto-format code with forge fmt [auto-format]"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}